services:
  db:
    image: postgres:14.3
    container_name: subsly-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: subsly
    volumes:
      - ./_postgres:/var/lib/postgresql/data